#!/bin/bash

################################################################
# Name: UPSTEAM Service Maker
# Written by: Jeaime Powell
# Creation date: 4/11/21
# Purpose: This script takes in a script file as input,
#        generates a .service file for it, and them saves it 
#        in /lib/systemd/system/ then reloads systemctl daemon
#################################################################

SCRIPT_NAME=$1

#Check for input
if [ -z "${SCRIPT_NAME}" ];then
	echo "Usage: service_maker.bash <scriptname>";
	exit
fi
echo "Is this the correct script(Y/n)? $SCRIPT_NAME"
while true; do
	echo "Please enter 'Y' for Yes or 'n' for No"
  	IFS= read -r result || exit # exit on EOF
  	case ${result} in
		Y) echo "You Selected Yes"
			break
			;;

		n) echo "You selected No. Exiting without changes"
		   exit 0
			;;
  	esac
  		echo >&2 Invalid choice.
done

CWD=$(pwd)
SCRIPTIN_CWD=true


echo "Checking for script file..."

if [ ! -f "$CWD/$SCRIPT_NAME" ]; then
	echo "Script not found in the current working directory $CWD"
	echo "Checking for script file in path given"
	SCRIPTIN_CWD=false
elif [ ! -f "$SCRIPT_NAME" ]; then
	echo "$SCRIPT_NAME not found. Check filename and path"
	exit 1;
else
	echo "Script path is found as: $CWD/$SCRIPT_NAME"
fi

read -e -p "Type a short Description of the service: " DESCRIPTION
while true; do
	echo -e "Do you accept this description? \n $DESCRIPTION"
	echo "Please enter 'Y' for Yes or 'e' for Edit or q for Quit (Y/e/q)"
  	IFS= read -r result || exit # exit on EOF
  	case ${result} in
		"") echo "The service can not have an empty description."
			echo "Please type a short descrption of the service."
			read -e -r DESCRIPTION
			;;
		Y) if [ -z "${DESCRIPTION}" ]; then
			echo "!!NOTE: YOUR SERVICE DESCRIPTION CAN NOT BE EMPTY!!"
			read -e -p "Type Description: " DESCRIPTION
		   else
			echo "You Selected Yes, creating the service file..."
			break
		   fi
		   ;;
		e) echo "You Selected Edit, Please renter your description."
			read -e -p "Type Description: " DESCRIPTION
			;;
		q) echo "You selected Quit. Exiting without changes"
		   exit 0
			;;

  	esac
  		echo >&2
done



FILENAME=$(echo $SCRIPT_NAME|sed 's/\./-/g')'.service'
echo "The service filename will be: $FILENAME"
touch $FILENAME


echo "# File Generated by service_maker.bash
[Unit]
Description=$DESCRIPTION
After=multi-user.target
Conflicts=

[Service]
Type=simple" > $FILENAME

if [ "$SCRIPTIN_CWD" = true ]; 
then
       echo "	
ExecStart=/usr/bin/python $CWD/$SCRIPT_NAME
StandardInput=tty-force

[Install]
WantedBy=multi-user.target" >> $FILENAME
else
       echo "	
ExecStart=/usr/bin/python $SCRIPT_NAME
StandardInput=tty-force

[Install]
WantedBy=multi-user.target" >> $FILENAME

fi

echo "All done, now copy the created file $FILENAME to '/lib/systemd/system/'"
echo "Then 'sudo systemctl daemon-reload'"
echo "To have the service run at startup sudo systemctl enable $FILENAME"
echo "To run the service run/stop the service sudo systemctl [start/stop] $FILENAME"
